server:
  port: 7778
customer:
  datasource:
#    url: jdbc:postgresql://localhost:3306/customer
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: PLSzW-2020
    ddl-mode: update
  allow-get-customer: true